---
- name: install packages
  ansible.builtin.package:
    name: '{{ desktop_packages }}'
    state: present
  become: yes
  tags:
  - desktop

#- name: update fontconfig
#  ansible.builtin.file:
#    path: /etc/fonts/conf.d/{{ item | basename }}
#    src: '{{ item }}'
#    owner: root
#    group: root
#    mode: 755
#    state: link
#  loop: '{{ desktop_fontconfig }}'
#  become: yes
#  tags:
#  - desktop

#- name: update gsettings
#  community.general.dconf:
#    key: '{{ item.key }}'
#    value: '{{ item.value }}'
#    state: present
#  loop: '{{ desktop_settings }}'
#  become: no
#  tags:
#  - desktop

# For some reason this worked in 36 using community dconf module but not for 37, command seems to do trick
#- name: set fractional scaling
#  command:
#    cmd: gsettings --schemadir /usr/share/glib-2.0/schemas  set org.gnome.mutter experimental-features '["scale-monitor-framebuffer"]'
#
