---
virtup:
  networks:
  - name: test
    domain: test.virt
    bridge: test-br1
    network: 192.168.99.1/24
  pools:
  - name: media
    path: /var/lib/libvirt/media
  - name: images
    path: /var/lib/libvirt/images
