---
desktop_packages:
- brasero
- chromium
- firefox-wayland
- gnome-epub-thumbnailer
- gnome-extensions-app
- gnome-tweak-tool
- xfreerdp
- yt-dlp

desktop_settings:
- key: /org/gnome/desktop/interface/clock-format
  value: "'12h'"
- key: /org/gnome/desktop/interface/clock-show-date
  value: 1
- key: /org/gnome/desktop/wm/keybindings/switch-windows 
  value: "['<Alt>Tab']"
- key: /org/gnome/mutter/experimental-features
  value: "['scale-monitor-framebuffer']"
